### ISSUE TITLE
Oauth integration

### ISSUE THREAD

**Issue by garouche** [SAPConversationalAI/Webchat#92]
Hello,

We're using the project and we saw that [requests to SAP public APIs will need Oauth authentication](https://blogs.sap.com/2020/12/02/why-and-how-to-migrate-your-chatbots-to-oauth-based-authentication/).
Will the project be updated to handle this ?

Thanks!

**Comment by jyguyomarch** [comment]
@garouche this change will not affect the WebChat as the WebChat is accessing via the Bot Connector and not directly via the mentioned APIs. So no update have been planned.

Don't hesitate to reopen this issue if you have more questions.
